# Generated by Django 3.2 on 2021-05-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.user'),
        ),
    ]
