# Generated by Django 3.2 on 2021-05-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_comment_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Tours', 'verbose_name_plural': 'Tours'},
        ),
    ]
